package com.cryptopilot.auth.service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.HexFormat;
import org.springframework.stereotype.Component;

/**
 * Makes the refresh token handed to a client, and the digest that is stored instead of it.
 *
 * <p>The same two properties the verification link has, for the same reasons: 256 bits from a
 * cryptographically secure generator, so a token cannot be found by trying; and never stored, so a
 * database that leaks yields nothing anyone can present. A lookup still works because the digest of
 * the presented value is what is searched for.
 *
 * <p>It is a separate class from {@link VerificationTokenFactory} rather than a rename of it, and
 * that is a decision rather than duplication left lying around. A verification token is a value put
 * in a link in an email; a refresh token is a credential a client stores for up to thirty days. They
 * are the same size today because 256 bits is right for both, and the day either one needs a
 * different length, encoding or generator, the other must not change with it. What is genuinely
 * shared — the SHA-256 digest — is the part the database defines, and both produce the identical
 * 64-character lower-case hexadecimal the column is sized for.
 *
 * <p>A plain random string rather than a second JWT: there is nothing to read in a refresh token, and
 * a signed one would be accepted on its own terms without a row in {@code user_token}, which is
 * exactly what rotation and family revocation need to be able to refuse.
 *
 * <p>Rule: TECHNICAL_DESIGN sections 5.3 and 7.15.
 *
 * <p>Reference: OWASP Application Security Verification Standard v4, section 3.2 (session tokens are
 * generated by a cryptographically secure generator and have at least 64 bits of entropy) and
 * section 2.5.
 * <p>Reference: Lodderstedt, T., Bradley, J., Labunets, A. &amp; Fett, D. (2025). <i>OAuth 2.0
 * Security Best Current Practice</i>, RFC 9700, section 4.14 (a refresh token is either
 * sender-constrained or rotated, and is stored so that a leaked store does not yield usable tokens).
 */
@Component
public class RefreshTokenFactory {

    /** 256 bits: the size TECHNICAL_DESIGN 5.3 states, and the size of the digest that stores it. */
    static final int TOKEN_BYTES = 32;

    private static final SecureRandom RANDOM = new SecureRandom();

    private static final Base64.Encoder URL_SAFE = Base64.getUrlEncoder().withoutPadding();

    /**
     * A fresh refresh token, to be handed to the client and then forgotten by the server.
     *
     * <p>Returned rather than stored: it goes into the sign-in response and nowhere else. It is never
     * logged and never put in an exception message.
     */
    public String newToken() {
        byte[] value = new byte[TOKEN_BYTES];
        RANDOM.nextBytes(value);
        return URL_SAFE.encodeToString(value);
    }

    /** The digest of a token, which is the only form of it that reaches the database. */
    public String digestOf(String token) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(token.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(digest);
        } catch (NoSuchAlgorithmException impossible) {
            throw new IllegalStateException("SHA-256 is required of every Java platform", impossible);
        }
    }
}
