package com.cryptopilot.auth.service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.HexFormat;
import org.springframework.stereotype.Component;

/**
 * Makes the value that goes into a verification link, and the digest that is stored instead of it.
 *
 * <p>Two properties matter. The value is unguessable: 256 bits from a cryptographically secure
 * generator, which is the same strength the refresh tokens of the design use, so a link cannot be
 * found by trying. And the value is never stored: what the database holds is its SHA-256 digest, so
 * a database that leaks yields nothing anyone can present. A lookup still works, because the digest
 * of the presented value is what is searched for.
 *
 * <p>The encoding is URL-safe Base64 without padding, because the value travels in a link; the
 * digest is lower-case hexadecimal, which is what {@code user_token.token_hash} is sized for and
 * what the entity insists on.
 *
 * <p>Rule: BR-01; TECHNICAL_DESIGN section 5.3.
 *
 * <p>Reference: OWASP Application Security Verification Standard v4, section 2.5 (a recovery or
 * verification token is generated by a cryptographically secure generator, has at least 64 bits of
 * entropy, is single use and time limited, and is stored only as a hash).
 */
@Component
public class VerificationTokenFactory {

    /** 256 bits, which is well past the entropy the standard asks for and matches the digest size. */
    private static final int TOKEN_BYTES = 32;

    private static final SecureRandom RANDOM = new SecureRandom();

    private static final Base64.Encoder URL_SAFE = Base64.getUrlEncoder().withoutPadding();

    /**
     * A fresh token, to be put in a link and then forgotten by the server.
     *
     * <p>Returned rather than stored, so the caller is the only thing that ever holds it: it goes
     * into the event that carries the mail and nowhere else. It is never logged and never returned
     * in a response.
     */
    public String newToken() {
        byte[] value = new byte[TOKEN_BYTES];
        RANDOM.nextBytes(value);
        return URL_SAFE.encodeToString(value);
    }

    /** The digest of a token, which is the only form of it that reaches the database. */
    public String digestOf(String token) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(token.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(digest);
        } catch (NoSuchAlgorithmException impossible) {
            throw new IllegalStateException("SHA-256 is required of every Java platform", impossible);
        }
    }
}
